# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TA9imZdVyl5gHYh9r8bRWroQt7Cwc8E
"""

import requests
import json
import os
import time
from datetime import datetime

# URLs
TOP_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Header required for API
headers = {"User-Agent": "TrendPulse/1.0"}

# Keywords for each category
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

MAX_LIMIT = 25


def find_category(title):
    title = title.lower()

    for cat in categories:
        for word in categories[cat]:
            if word in title:
                return cat
    return None


def get_top_ids():
    try:
        res = requests.get(TOP_URL, headers=headers)
        return res.json()[:500]
    except:
        print("Error getting top stories")
        return []


def get_story(id):
    try:
        url = ITEM_URL.format(id)
        res = requests.get(url, headers=headers)
        return res.json()
    except:
        print(f"Skipping story {id}")
        return None


def main():
    ids = get_top_ids()

    data = []
    count = {c: 0 for c in categories}

    print("Starting data collection...")

    for sid in ids:
        story = get_story(sid)

        if not story:
            continue

        title = story.get("title", "")
        cat = find_category(title)

        if not cat:
            continue

        if count[cat] >= MAX_LIMIT:
            continue

        item = {
            "post_id": story.get("id"),
            "title": title,
            "category": cat,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by", "unknown"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        data.append(item)
        count[cat] += 1

        print(f"Added: {title[:50]}... -> {cat}")

        if all(count[c] >= MAX_LIMIT for c in count):
            print("All categories filled!")
            break

    if not os.path.exists("data"):
        os.makedirs("data")

    filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)

    print("\nDone!")
    print(f"Collected {len(data)} stories")
    print(f"Saved to {filename}")


if __name__ == "__main__":
    main()

import os
os.listdir("data")

import json

with open("data/trends_20260414.json") as f:
    data = json.load(f)

print(len(data))        # should be 100+
print(data[0])          # check structure

from google.colab import files
files.download("data/trends_20260414.json")